services:

  # Interface autowiring
  DigitalCraftsman\DateTimePrecision\Clock\Clock: '@DigitalCraftsman\DateTimePrecision\Clock\SystemClock'

  DigitalCraftsman\DateTimePrecision\Clock\SystemClock:
    class: DigitalCraftsman\DateTimePrecision\Clock\SystemClock
