services:

  DigitalCraftsman\DateTimePrecision\Serializer\DateTimeNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\DateTimePrecision\Serializer\TimeNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\DateTimePrecision\Serializer\DateNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\DateTimePrecision\Serializer\MonthNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\DateTimePrecision\Serializer\YearNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]
