services:

  DigitalCraftsman\DateTimeUtils\Serializer\DateTimeNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\DateTimeUtils\Serializer\TimeNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\DateTimeUtils\Serializer\DateNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\DateTimeUtils\Serializer\MonthNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]
